### ISSUE TITLE
getting 403 error when working with shared access signature

### ISSUE THREAD

**Issue by pradeepramagiri** [Azure/azure-storage-net-data-movement#114]
I am using below code to upload data blob using sas url. I am getting 403 error when uploading. tell me where I am doing wrong?
CloudBlobContainer container = new CloudBlobContainer(endpointUri);
                CloudBlockBlob blob = container.GetBlockBlobReference(Path.GetFileName(inputeFileLocation));
                blob.ServiceClient.AuthenticationScheme = AuthenticationScheme.SharedKey;
                TransferManager.Configurations.ParallelOperations = Environment.ProcessorCount * 8;
                SingleTransferContext singleTransferContext = new SingleTransferContext();
                long totalBytes = new FileInfo(inputeFileLocation).Length;
                singleTransferContext.ProgressHandler = new Progress<TransferStatus>((progress) =>
                {
                    OnByteTransfered(new BytesTransferedEventArgs() { TotalBytes = totalBytes, TotalBytesTransfered = progress.BytesTransferred });
                });
                UploadOptions uploadOptions = new UploadOptions()
                {
                    DestinationAccessCondition = AccessCondition.GenerateIfNotExistsCondition()
                };
                try
                {
                    await TransferManager.UploadAsync(inputeFileLocation, blob, null, singleTransferContext);
                    blobOperationStatus.OperationStatus = OperationStatus.Succeded;
                }
                catch(Exception ex)
                {
                    blobOperationStatus.OperationStatus = OperationStatus.Failed;
                }

**Comment by pradeepramagiri** [comment]
how to upload file using container sas token with this library?

**Comment by jiacfan** [comment]
Hi, @pradeepramagiri 

403 Forbidden is typically caused by authentication failure, please ensure the SAS has enough permission to create and write blob in the specified container, and please ensure the container itself already exists(as it needs additional create container permission), for more details about SAS permission please refer to [How to construct service SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/Constructing-a-Service-SAS?redirectedfrom=MSDN) and [How to construct account SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-an-account-sas)

If you are not clear if your SAS get enough permission, please share your SAS information(note: **please eliminate the sig= query parameter**), and we can help to have a look.

An easy way to validate if SAS has enough permission, you can call Azure storage client library's `blockBlob.UploadFromFile()` in your code, and see if it can work or same error reported as well.

To use container SAS in DMLib:
```
CloudBlockBlob blob = new CloudBlockBlob(new Uri("https://jiacstgwestcentralus01.blob.core.windows.net/testcontainer01/testaaa?st=2018-02-15T08%3A30%3A00Z&se=2018-02-20T08%3A30%3A00Z&sp=rwdl&sv=2016-05-31&sr=c&sig=<Replaced>"));
TransferManager.UploadAsync(@"c:\Test.pdf", blob).Wait();
```

Best Wishes,
Jiachen

**Comment by Prarama** [comment]
Hi,@Jiachen
Yes, its an issue with sas token permission. Its working fine with list and write permissions.
I am able to upload files with proper permission Thank you for you help.
