### ISSUE TITLE
Synchronous copy between different storage accounts

### ISSUE THREAD

**Issue by GFoley83** [Azure/azure-storage-net-data-movement#12]
AzCopy allows for synchronous copy between storage accounts:
http://blogs.msdn.com/b/windowsazurestorage/archive/2015/01/13/azcopy-introducing-synchronous-copy-and-customized-content-type.aspx

Is there an way to achieve this with azure-storage-net-data-movement? 
i.e. through C# code and not the command line?

Scenario: I have 2 storage accounts. A 3rd party service places files on temp storage account A. 
When I know the files are on A, I need to copy them to my main storage account B.
I don't want to give the 3rd party access to storage account B for security.

**Comment by nowenL** [comment]
azure-storage-net-data-movement library (DMLib for short) also allow synchronous copy between storage accounts.

You can synchronous copy a source blob under account A to a destination blob under account B with following codes:
                
            CloudBlob sourceBlob; /* source blob from account A */
            CloudBlob destinationBlob; /* destination blob from account B */

            Task task = TransferManager.CopyAsync(sourceBlob, destinationBlob, false /* isServiceCopy */);

            task.Wait();
       
The 3rd parameter is “isServiceCopy”, DMLib will use synchronous copy (download to local and upload) if it’s set to false. Otherwise, the blob will be copied in service side. The “Async” in the function name “CopyAsync” means it’s an async C# function.
Note that the currently DMLib only support to copy a single blob. You need to list the blobs under account A with your own codes and invoke DMLib if you need to copy all blobs under account A.

**Comment by markjbrown** [comment]
How would I replicate what you guys did for incremental copy in AzCopy (using the /XO switch)?

I thought initially I should use CopyOptions and set IfModifiedSinceTime but that doesn't work because there is no comparison of source and destination blob properties. (it actually just throws Transfer Failed errors when the condition isn't met).

So in AzCopy do you just check the blob property ModifiedSince value between the source and the destination and only copy if the source is newer when /XO is set?

Thanks,
Mark

**Comment by nowenL** [comment]
Hi, Mark

"IfModifiedSinceTime" in source/destination AccessCondition of CopyOptions is the conditional header for azure blob/file operations. Once it's specified, DMLib will simply use the conditional header in the request sent to source/destination. Thus if the condition isn't met, service generally returns a 412 error and causes the transfer fail. You can find detailed information here: https://msdn.microsoft.com/en-us/library/azure/dd179371.aspx

In AzCopy, we compare the LastModified property of source and destination and skip the older source if /XO is set. You need to do it as well before calling DMLib to start the transfer if you'd like to do the incremental copy.

One alternative is you can do the modified time comparison and choose not to overwrite a newer destination in the OverwriteCallback. Since the source and destination URI are provided there, it might save you some efforts.

**Comment by markjbrown** [comment]
Got it. Thanks

**Comment by GFoley83** [comment]
@nowenL I really don't want to have to download a copy of the source file locally, or even on the server before copying to the destination storage account as some of the file are pretty large > 5GB. 
If I set `isServiceCopy` to true, will this copy the file directly from the Azure source storage to destination storage on that different account? If not, is there anyway to accomplish this?

**Comment by nowenL** [comment]
@GFoley83 Yes, if 'isServiceCopy' is set to true, the blobs will be copied directly from your source storage account into your destination storage account. The data transfer is happening in azure storage server and what DMLib do afterwards is only monitoring the copy progress. However, the 'ServiceCopy' uses the spare bandwidth of storage server so there's no SLA for the copy speed. You can find more details about the server side blob copy here: http://blogs.msdn.com/b/windowsazurestorage/archive/2012/06/12/introducing-asynchronous-cross-account-copy-blob.aspx

**Comment by GFoley83** [comment]
This solved my problem, thank you.

**Comment by alexsandro-xpt** [comment]
@nowenL `TransferManager.CopyAsync` method copy only single CloudBlob at the time, right?

With AzCopy I could copy an entire Container to another Container, how can I could do that with Data Movement?

**Comment by scgough** [comment]
@alexsandro-xpt is this what you are looking for: `CopyDirectoryAsync`
See: https://github.com/Azure/azure-storage-net-data-movement/issues/20

**Comment by afkhan517** [comment]
Hi All,
The size of my source directory is 200 mb and making isServiceCopy to "false" will first download and then upload which again taking too long time as compared to isServiceCopy "true" and sometimes internet speed is also too weak and downloading and uploading 200 mb file takes long time.
Currently copying directory using azurefileshare takes 5.23 min and copying the same using normal file copy(File.Copy) takes 3 min.
It would be a great help if you suggest something related to isServiceCopy "true" or any other way.
Thanks in advance.
Please help asap.
