### ISSUE TITLE
Does TransferManager.CopyAsync support retry on copy operation? 

### ISSUE THREAD

**Issue by payiAzure** [Azure/azure-storage-net-data-movement#137]
Want to use TransferManager.CopyAsync() to copy CloudBlob/CloudFile from one container to another container. Does this API support the retry copy if the blob/file copy failed?

I notice that in Azure DataMovement, there is a class 'Transfer_RequestOptions', which can set the retry option and retry policy. Is there a way to make use of the Transfer_RequestOptions in TransferManager.CopyAsync to make the copy retry-able?  I looked at samples, but couldn't figure out.

**Comment by blueww** [comment]
@payiAzure 

If you copy Sync (isServiceCopy = false) or Async (isServiceCopy = true)? 
The retry policy is for send request from DMlib to Azure Server. 

- For Sync Copy, it's actually download to local memory and upload, so the retry policy will use used in the copy.
- But for Async Copy, the copy is controlled by server side, and server won't the retry policy in DMlib. Actually AsyncCopy has no SLA, DMlib can only start the copy, and retrieve the copy result.

If you want to use the retry policy in Copy, and want the copy can be resume if break in the middle, you can use SyncCopy (isServiceCopy = false). 
If you want to

**Comment by payiAzure** [comment]
@blueww I see. Thank you blueww. 
1. So with isServiceCopy = false, when retrieve the copy status is "Failed", the 'retry copy' will be automatically started? Is it a infinite retry until the copy succeeded, or we can config the retry count?
2. I looked at the API 'public static Task CopyAsync(CloudBlob sourceBlob, CloudBlob destBlob, bool isServiceCopy)', what is the retry policy? how can we config the retry policy?
 3. Is there any example for doing retry on copy using SyncCopy(isServiceCopy = false)?

**Comment by payiAzure** [comment]
@blueww Another question about the copy SLA.
As you mentioned if use Async copy (isServiceCopy = true), there is no SLA. So the copy doesn't guarantee the copy time? Can you point me more details of the SLA?

If use Sync copy (isServiceCopy = false), there is SLA? What is the SLA?

**Comment by blueww** [comment]
For you questions:
1. Yes

2. Would you please share why you want to change the retry policy? The current retry policy is for max the success rate of transfer. And if you need, you can pull DMlib code, then change the retry policy as you need in your local code, and build you own dmlib binary on your own machine. We don't prefer you submit your retry policy back to common DMlib code, since it might not be applicable for every DMlib user. Anyway, we have a request to open the customized retry policy https://github.com/Azure/azure-storage-net-data-movement/issues/125. 


For SLA, see more detail in https://azure.microsoft.com/en-us/support/legal/sla/storage/v1_3/
And you can see, copy blob only has SLA (90s) whem the source and dest are in same account, else the copy time can't be guarantee.
If you use SyncCopy, it's actually upload and download. You can see upload and download has SLA in the doc.

**Comment by payiAzure** [comment]
@blueww For bullet 2, probably we won't go with changing the retry policy in DMlib. 

We need to use Async copy in our copy operations. Since our work is part of control service, if we use sync copy, the service will be hold until the copy the done, which is not acceptable in our service.
We will add our own retry logic in our service side code to re-issue the copy request.

**Comment by payiAzure** [comment]
@blueww Thanks Wei Wei. Yes, I think this issue can be closed.
