### ISSUE TITLE
404 when using a SAS in local storage

### ISSUE THREAD

**Issue by lehne** [Azure/azure-storage-net-data-movement#15]
When I try to use a SAS to write a blob from the client library to development storage, I get a 404 error saying that blob cannot be found. I can change the permissions of the SAS but to no effect. It worked fine when I used UploadAsync but now that I am trying the movement library it doesn't work. I'm wondering if the SAS is not getting sent when using PutBlock? Or is there something that I need to do first?

**Comment by nowenL** [comment]
@lehne 
You mentioned it worked fine with UploadAsync, do you mean the UploadAysnc function in data movement library works with key credentials but fails with SAS? 

Can you provide more details about how you get the 404 error?
1. What kind of SAS is used here, container SAS, blob SAS or account SAS.
2. Permissions of SAS. Note that DMLib requires both read and write permissions for destination blob since it need to check whether the destination exist or not for overwrite.
3. DMLib method and parameter used. A sample code about how the sas is generated and passed into DMLib would be best.

FYI. The following codes work for me.
1. SAS generation

            CloudBlobContainer container = azureClient.GetContainerReference("debug");

            SharedAccessBlobPolicy sasPolicy = new SharedAccessBlobPolicy();
            sasPolicy.Permissions = SharedAccessBlobPermissions.Read | SharedAccessBlobPermissions.Write;
            sasPolicy.SharedAccessExpiryTime = DateTimeOffset.Now.AddSeconds(3600);

            string sasToken = container.GetSharedAccessSignature(sasPolicy);

2. Call dmlib

            StorageCredentials sasCred = new StorageCredentials(sasToken);
            CloudBlockBlob destBlob = new CloudBlockBlob(destBlobUri, sasCred);

            TransferManager.UploadAsync(@"C:\temp\test.txt", destBlob).Wait();

**Comment by vinjiang** [comment]
Feel free to reopen it if you still need assistance on this issue.
