### ISSUE TITLE
Copying Containers Functionality?

### ISSUE THREAD

**Issue by isaac2004** [Azure/azure-storage-net-data-movement#20]
Is there a task in the pipeline to add support to copy all blobs from an existing container? Using AzCopy, we can pass the container name as part of the Uri and it will move all blobs in that container to another defined container. Is this supported by the new Data Movement library?

**Comment by nowenL** [comment]
Yes. It's already supported since v0.2.0. You can use TransferManager.CopyDirectoryAsync to copy multiple blobs with new dmlib just like AzCopy. A simple example for you reference:

            CloudBlobDirectory sourceDirectory = container.GetDirectoryReference(string.Empty);
            CloudBlobDirectory destDirectory = container2.GetDirectoryReference(string.Empty);

            CopyDirectoryOptions options = new CopyDirectoryOptions()
            {
                Recursive = true
            };

            TransferManager.CopyDirectoryAsync(sourceDirectory, destDirectory, true /*isServiceCopy*/, options, null /*transferContext*/).Wait();

You can find more samples for directory transfer in our sample project:
https://github.com/Azure/azure-storage-net-data-movement/tree/master/samples/DataMovementSamples

**Comment by vinjiang** [comment]
Feel free to reopen it if you still need assistance on this issue.

**Comment by alexsandro-xpt** [comment]
@nowenL I try run this example and it's so slow, and by the way it's using my internet network to download and upload the blobs to destination container.

What is wrong?

**Comment by EmmaZhu** [comment]
@alexsandro-xpt 
By running the example, do you mean to copy blob between different accounts or to download/upload blobs? Could you share the code you used?
We are tracking different questions with different issues, it'd be easier for us to track the questions if you could open a new issue instead of reply in a closed one. I've opened [a new issue here](https://github.com/Azure/azure-storage-net-data-movement/issues/68). Thanks for your cooperation.
