### ISSUE TITLE
ParallelOperations and DefaultConnectionLimit

### ISSUE THREAD

**Issue by markjbrown** [Azure/azure-storage-net-data-movement#23]
I am implementing the ParallelOperations property on the TransferManager. I have run a number of tests with it set to different values (8, 16, 32, 64) and the results are confusing and inconsistent. 

Is there any guidance for how to determine what this value should be?

Do I (or can I) set this value in conjunction with ServicePointManager.DefaultConnectionLimit where it is equal to Environment.ProcessorCount * 8? I want to make sure the ParallelOperations property is tuned to the VM it is running in.

Also, why is your guidance for DefaultConnectionLimit = Environment.ProcessorCount * 8? The guidance I have seen for this suggests it should be Environment.ProcessorCount * 12.

Thanks.

**Comment by nowenL** [comment]
The default value of ParallelOperations is ProcessorCount * 8. It's proven to be a reasonable setting in our test. It provides considerable parallel data transfer meanwhile doesn't stress the azure service too much. We suggest to set DefaultConnectionLimit  to ProcessorCount * 8 as well, otherwise the connection can be the performance bottleneck since there are not enough connections to serve the parallel transfer. In brief, the recommended setting for ParallelOperations and DefaultConnectionLimit is leave ParallelOperations with the default value and set DefaultConnectionLimit to ProcessorCount * 8 (Same value as ParallelOperations).

**Comment by markjbrown** [comment]
Perfect. Thank you!
