### ISSUE TITLE
Add GzipStream support

### ISSUE THREAD

**Issue by blrchen** [Azure/azure-storage-net-data-movement#34]
I am now using DM library to move big files from on-premise to Azure storage, once the data is in cloud, it will be consumed by Hive and Spark. Since both Hive and Spark support decompress and read gzip compressed files, am thinking if DM can support GzipStream when uploaded to cloud?

**Comment by nowenL** [comment]
DM Library now supports to upload to Azure storage from a stream. The blocker for using a GzipStream  is it requires the stream to be seekable and have a fixed length. 

I think it's possible to remove the seekable requirement since seek is only used when resume a transfer while upload from stream doesn't support resume at all. 

Fixed length is also not necessary for block blob and append blob, but it's a must-have for page blob and cloud file since their creation requires the object size.

It would be great if we can remove such limitations and unblock the scenario you mentioned. I will add this into our backlog and investigate it in our following releases.

**Comment by blrchen** [comment]
In my scenarios, only block blobs have the requirement to be gzip streamed to cloud.

**Comment by vinjiang** [comment]
@blueww , please share latest update on stream.

**Comment by blueww** [comment]
@blrchen 
The latest AzCopy 7.1 release has supported upload block blob from none-seekable  stream.
Would you like to have a try? Let me know if you have further questions.

Best Wishes
Wei Wei

**Comment by blueww** [comment]
@blrchen 

As we don't hear any more request from you for a long time,  I will close the issue now.
Please contact us if you need further assistance.
