### ISSUE TITLE
Copy directory from File Storage to Blob Storage is much slower than AzCopy

### ISSUE THREAD

**Issue by arneeiri** [Azure/azure-storage-net-data-movement#55]
Copying a File Storage directory using DML I would expect comparable performance to what I get when I do the same with AzCopy.

When I copy around 4500 files sized between 5KB and 150KB within the same Storage Account it takes around 90 seconds from AzCopy.  From DML it takes around 400 seconds. Some times it even times out inside an Azure Storage library.

I set the parameter isServiceCopy to true in my method call. But I have a hypothesis that it actually downloads everything to my computer and uploads it again. I base this on inspecting my network activity during operation. It is around 400-500 Kbps during the transfer and it drops to almost zero when it is done.

The command I run from AzCopy is this.
`> azcopy /Source:"https://<myAccount>.file.core.windows.net/fileshare/folder/" /SourceKey:<key> /Dest:"https://<myAccount>.blob.core.windows.net/container/folder" /DestKey:<key> /S`

This is taken from my source code using DML:
```
TransferManager.Configurations.ParallelOperations = 64;
ServicePointManager.DefaultConnectionLimit = Environment.ProcessorCount * 8;
ServicePointManager.Expect100Continue = false;
var result = await TransferManager.CopyDirectoryAsync(fileDirectory, cloudBlobDirectory, true, new CopyDirectoryOptions {Recursive = true}, new DirectoryTransferContext());
```

**Comment by blueww** [comment]
For the following setting, do you set it in the beginning of your program (before you send any azure request like create container)? It will only take effect when you set it before send any azure request.
```
ServicePointManager.DefaultConnectionLimit = Environment.ProcessorCount * 8;
ServicePointManager.Expect100Continue = false;
```

When you set isServiceCopy to true, it's actually server side copy. If you want downloads everything to your computer and uploads it again, you should set isServiceCopy to false (In Azcopy, add /syncCopy ).
For the  network 400-500 Kbps during the transfer , it's caused by the file size is small so the overhead (e.g. send copy request and check copy status) will be relatively high.

**Comment by arneeiri** [comment]
I set the DefaultConnectionLimit and Expect100Continue immediately before I call TransferManager.CopyDirectoryAsync. I have also tried to isolate it from my application so that no other network requests are made concurrently.

This gave the same type of results.

**Comment by blueww** [comment]
Please make sure you set the DefaultConnectionLimit and Expect100Continue, in the beginning of the program, before you send any request to azure server, like get container properties, create container, get Share properties, create Share ....
You should call them in the beginning of your application, instead of immediately before TransferManager.CopyDirectoryAsync.

I am not sure what you mean by " isolate it from my application ", if you can share your code (hide credential), it will help us on the investigation. But what we need is no network requests happen before the settings are set.

**Comment by arneeiri** [comment]
I understand. I have tried putting the DefaultConnectionLimit and Expect100Continue at the very beginning of my program and i have also tried putting it just before I call into DML. The results were the same in both ways.

I have pushed a very simplified project that reproduces the issue for me. You can find the code here: https://github.com/arneeiri/dml-copy-reproduce/blob/master/DmlCopyRepro/ConsoleApplication1/Program.cs

**Comment by blueww** [comment]
I have tried your code on my machine with DMlib 0.4 and AzCopy 5.0 (I don't use 5.1 since 5.1is based on DMlib 0.4 and should have same behavior). And find they have similar behavior:
When destination files not exist (but container exist), async Copy 4500 * 5KB File -> blob in same storage account with http protocal:
DMlib: 91.5s
AzCopy: 86s

Please help to share the DMlib and AzCopy version you use.
One thing you can check is the protocal (http or https) , and account name used in DMlib and AzCopy are same.
And please notice the Async Copy performance is also highly based on server behavior.

**Comment by arneeiri** [comment]
I ran them again now.
DMlib: 354.7s
AzCopy: 74s
Both runs where done within ~5 minutes. So server load should probably not be an issue. I have also had this kind of results consistently for the last three days.

I use AzCopy 5.0.0. I use DMlib 0.4.0. The rest of the deps can be found in https://github.com/arneeiri/dml-copy-reproduce/blob/master/DmlCopyRepro/ConsoleApplication1/packages.config.

As I showed in my previous comment I use HTTPS with AzCopy. For DMlib I use HTTPS too. (connection string starts with: DefaultEndpointsProtocol=https;)

My computer runs Windows 8.1 and uses .NET Framework 4.5.2.

**Comment by blueww** [comment]
I run async Copy 4500*5KB File->Blob in same account again with https. Each run 3 times:
DMlib 0.4: 90s, 88s, 87s
AzCopy 5.0: 88s, 88s, 87s

You can see the time is still very similar.

Would you please try to use AzCopy 5.1 (http://aka.ms/downloadazcopy) with same paramter of AzCopy 5.0, to see how it works on you machine. As it's based on DMlib 0.4, it should have same behavior with DMlib 0.4.
